name: workflow_secrets
on:
  workflow_dispatch:
env:
  DB_U: ${{ secrets.DB_U }}
  DB_P: ${{ secrets.DB_P }}

jobs:
  test-secrets:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: checkout env u
        run: echo "u=${{ env.DB_U}}"
      - name: checkout env p
        run: echo "p=${{ env.DB_P}}"